# OpenAPI Generator config (php)
# Generated output goes to: sdks/php
invokerPackage: Alexasomba\\Paystack
composerPackageName: alexasomba/paystack
packageName: Paystack
artifactVersion: 1.1.0
gitHost: github.com
gitUserId: alexasomba
gitRepoId: paystack-openapi
hideGenerationTimestamp: true
